### ISSUE TITLE
Name Collisions

### ISSUE THREAD

**Issue by schambersnh** [jpmayer/fantasy-chrome-extension#100]
My dad and I have the same name, and that is causing issues since managers are defined by their name. 

**Power Rankings**
I cannot submit power rankings because my team shows up twice, and my dads team does nto show up at all.

**Leaderboard**
Both of our stats are aggregated

I have changed my name to 'xxxx jr' in my ESPN account, deleted the extension, and reopened it, but that did not seem to solve the problem. Love this extension, but cannot use it until this is resolved.

I saw three other instances on the reddit post of this happening to other people. Thanks for the hard work.

**Comment by bizzleburger** [comment]
Hey man, thanks for the feedback. We have an open issue for this already #76 if you'd like to track that for progress. We're working on a fix now. If you have renamed your team, try running deleting the DB and reuploading it. Feel free to add a comment to the previous issue to keep track.
