### ISSUE TITLE
Implement current scoring period

### ISSUE THREAD

**Issue by bizzleburger** [jpmayer/fantasy-chrome-extension#20]
Need to use a better mechanism to keep track of current week of season. Should use `scoringPeriodID` attr in the `com.espn` API object, found by @jpmayer.

Current method causes issues with half-completed weeks and updates.

**Comment by jpmayer** [comment]
https://github.com/jpmayer/fantasy-chrome-extension/commit/377e4547ebbf0d419377fc30dc2a721edf6ef76a
