### ISSUE TITLE
Screenshot popup failing intermittently 

### ISSUE THREAD

**Issue by bizzleburger** [jpmayer/fantasy-chrome-extension#32]
Occasionally, the popup for the screenshots will fail to load an image. No error in console either. Happens on first few tries then seems like it works every time.

**Comment by bizzleburger** [comment]
Possible fix could be to enact a handshake between the screenshot and popup pages.

**Comment by jpmayer** [comment]
https://github.com/jpmayer/fantasy-chrome-extension/pull/48
