### ISSUE TITLE
Close tab after image is downloaded

### ISSUE THREAD

**Issue by bizzleburger** [jpmayer/fantasy-chrome-extension#4]
New tab opened for screenshots should be closed once the images has been downloaded.

**Comment by bizzleburger** [comment]
Should add the option to close tab after the image has been downloaded.

**Comment by jpmayer** [comment]
https://github.com/jpmayer/fantasy-chrome-extension/pull/48

**Comment by jpmayer** [comment]
Not closing window anymore until the next time an image is generated
