### ISSUE TITLE
Error processing SQL: could not prepare statement (1 no such table: matchups)

### ISSUE THREAD

**Issue by bizzleburger** [jpmayer/fantasy-chrome-extension#77]
Could be caused by several different things, it's being reported in a few different circumstances.

- Not all teams have accepted invites
- Non standard team formats
- Leagues with history pre-2006/2007

**Comment by mjrode** [comment]
I believe that we can use this mapping to fix the non-standard team formats. If we use the mapping listed below we can move away from relying on the array position to determine the players position. 

I primary work in Ruby but I will attempt to get a PR together w/ the fix. Here is a list of the mapping for reference: 

`  roster_map = {
                      0: 'QB',
                      1: 'TQB',
                      2: 'RB',
                      3: 'RB/WR',
                      4: 'WR',
                      5: 'WR/TE',
                      6: 'TE',
                      7: 'OP',
                      8: 'DT',
                      9: 'DE',
                      10: 'LB',
                      11: 'DL',
                      12: 'CB',
                      13: 'S',
                      14: 'DB',
                      15: 'DP',
                      16: 'D/ST',
                      17: 'K',
                      18: 'P',
                      19: 'HC',
                      20: 'BE',
                      21: 'IR',
                      22: '',
                      23: 'RB/WR/TE'
                      }`

**Comment by jpmayer** [comment]
Thanks for looking into this! One issue i see right off the bat though is that in standard league the bench (BE) is mapped to 20 not 21 and WR are 4 not 5. This looks like it could be the mapping for IDP leagues or possibly non standard leagues in general im not sure.

Also the mapping we have been going off of is in decimal notation "4.0" vs "4"

Care to share where you found this mapping? I dont really know where to start looking

**Comment by jpmayer** [comment]
We got the standard mapping from this post: https://stmorse.github.io/journal/espn-fantasy-2-python.html

Also forget what i said about decimals, not sure why our mapping is written in them actually, we may be doing something overdone there. As it appears to be coming in in integer format. Ill look into that further too

**Comment by jpmayer** [comment]
Start of fix:
https://github.com/jpmayer/fantasy-chrome-extension/commit/a2ce46fee99d08da39c802f5020becbcb8c5d2ed

Moving away from boxscore API that uses those mappings and using instead the quickboxscore HTML to get player data. This solves another problem by allowing us to query before 2017 which the boxscore API does not allow. It is a slower process but offers more data and flexibility

**Comment by jpmayer** [comment]
https://github.com/jpmayer/fantasy-chrome-extension/commit/a2ce46fee99d08da39c802f5020becbcb8c5d2ed
