### ISSUE TITLE
Playoff Appearances incorrect after enabling tracking of Losers Bracket and 3rd Place games

### ISSUE THREAD

**Issue by zachpepsin** [jpmayer/fantasy-chrome-extension#95]
After enabling Losers Bracket and 3rd Place games, the Playoff Appearances values are not calculated correctly

**Comment by jpmayer** [comment]
Thanks! Found the issue, was doing a > case and needed to be >=

Fix will be in version 1.1.4

**Comment by jpmayer** [comment]
https://github.com/jpmayer/fantasy-chrome-extension/commit/fccc4bae300aea09176800b8abd537db828cc636
